# -*- coding: utf-8 -*-
"""english_to_french_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2y6k35WGGHkzQZ-J3IRWs0woH_2AJ9k
"""

!pip install transformers sentencepiece --quiet

import time
from transformers import pipeline

translator = pipeline(
    "translation",
    model="facebook/m2m100_418M",
    src_lang="en",
    tgt_lang="fr"
)

def type_print(text, delay=0.05):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

print("Welcome to the English → French Chatbot!")
print("Type 'exit' to quit.\n")

while True:
    user_input = input("You: ")
    if user_input.lower() == 'exit':
        print("Chatbot: Au revoir! 👋")
        break

    translation = translator(user_input)[0]['translation_text']

    print("Chatbot: ", end='')
    type_print(translation)