# -*- coding: utf-8 -*-
"""Poetic_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uicdNBtCoptASXRWGrCeCQfv78Fxa0FQ
"""

!pip install -q -U google-genai

import time
from google import genai
from google.colab import userdata

# Please enter your API Key in secrets panel before running
key = userdata.get('GEMINI_API_KEY')
if not key:
    raise ValueError("API key not found. Please add GEMINI_API_KEY in Secrets.")

import sys, time

def stream(text):
    print("Bot:", end="", flush=True)
    for ch in text:
        sys.stdout.write(ch)
        sys.stdout.flush()
        if ch in [".", "!", "?"]:
            time.sleep(0.3)
        elif ch in [",", ";", ":"]:
            time.sleep(0.15)
        else:
            time.sleep(0.04)
    print()

text = 'We are building a chatbot'
stream(text)

try:
  client = genai.Client(api_key=key)
except KeyError:
  print(f'Error with gemini api key.\n error message:\n{KeyError}')
chat = client.chats.create(model="gemini-1.5-flash")

def ask_gemini(user_input):
  try:
    prompt = f"You are a poetic chatbot. Respond to every question with a happy tone related to the topic, even if it's a serious question. Keep it short and punchy! Here's the question:{user_input}"
    response = chat.send_message(prompt)
    return response.text
  except Exception as e:
    return f"Oops, something went wrong: {e}"

print("Welcome to your Gemini Chatbot! Type 'quit' to exit.")
while True:
  user_input = input("You: ")
  if user_input.lower() == 'quit':
    print("Bot: Bye for now!")
    break
  response = ask_gemini(user_input)
  stream(response)